// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _2026_PinRu_backend.Data;

#nullable disable

namespace _2026_PinRu_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213130803_AddBookingAndRoomSchema")]
    partial class AddBookingAndRoomSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_2026_PinRu_backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            EndTime = new DateTime(2026, 2, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            RoomId = 1,
                            StartTime = new DateTime(2026, 2, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("_2026_PinRu_backend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jakarta",
                            CreatedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "budi@mail.com",
                            IsDeleted = false,
                            Name = "Budi Santoso",
                            Phone = "08123456789",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Surabaya",
                            CreatedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "siti@mail.com",
                            IsDeleted = false,
                            Name = "Siti Aminah",
                            Phone = "08223456789",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bandung",
                            CreatedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andi@mail.com",
                            IsDeleted = false,
                            Name = "Andi Wijaya",
                            Phone = "08323456789",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Medan",
                            CreatedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dewi@mail.com",
                            IsDeleted = false,
                            Name = "Dewi Lestari",
                            Phone = "08423456789",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Semarang",
                            CreatedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eko@mail.com",
                            IsDeleted = false,
                            Name = "Eko Prasetyo",
                            Phone = "08523456789",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("_2026_PinRu_backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            IsAvailable = true,
                            Location = "Lantai 1",
                            Name = "Ruang Meeting A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 100,
                            IsAvailable = true,
                            Location = "Lantai 2",
                            Name = "Aula Utama"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            IsAvailable = true,
                            Location = "Lantai 3",
                            Name = "Laboratorium Komputer"
                        });
                });

            modelBuilder.Entity("_2026_PinRu_backend.Models.Booking", b =>
                {
                    b.HasOne("_2026_PinRu_backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_PinRu_backend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
