// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _2026_PinRu_backend.Data;

#nullable disable

namespace _2026_PinRu_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209085507_InitialFullSetup")]
    partial class InitialFullSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_2026_PinRu_backend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jakarta",
                            CreatedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "budi@mail.com",
                            IsDeleted = false,
                            Name = "Budi Santoso",
                            Phone = "08123456789",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Surabaya",
                            CreatedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "siti@mail.com",
                            IsDeleted = false,
                            Name = "Siti Aminah",
                            Phone = "08223456789",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bandung",
                            CreatedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andi@mail.com",
                            IsDeleted = false,
                            Name = "Andi Wijaya",
                            Phone = "08323456789",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Medan",
                            CreatedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dewi@mail.com",
                            IsDeleted = false,
                            Name = "Dewi Lestari",
                            Phone = "08423456789",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Semarang",
                            CreatedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eko@mail.com",
                            IsDeleted = false,
                            Name = "Eko Prasetyo",
                            Phone = "08523456789",
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
